language: node_js

node_js:
 - "7"

os:
 - linux
 - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libicu-dev
      - g++-4.8

cache:
  directories:
    - npm_modules


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install icu4c      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link icu4c --force ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then export CXX=g++-4.8      ; fi
